### ISSUE TITLE
ros_mpeg321_player fails to build due to bad install rule

### ISSUE THREAD

**Issue by tfoote** [ROBOTIS-GIT/ROBOTIS-Utility#4]
From: http://build.ros.org:8080/view/Queue/job/Kbin_uxhf_uXhf__ros_mpg321_player__ubuntu_xenial_armhf__binary/37/console

```
10:22:09 Install the project...
10:22:09 /usr/bin/cmake -P cmake_install.cmake
10:22:10 -- Install configuration: "None"
10:22:10 -- Installing: /tmp/binarydeb/ros-kinetic-ros-mpg321-player-0.1.0/debian/ros-kinetic-ros-mpg321-player/opt/ros/kinetic/lib/pkgconfig/ros_mpg321_player.pc
10:22:10 -- Installing: /tmp/binarydeb/ros-kinetic-ros-mpg321-player-0.1.0/debian/ros-kinetic-ros-mpg321-player/opt/ros/kinetic/share/ros_mpg321_player/cmake/ros_mpg321_playerConfig.cmake
10:22:10 -- Installing: /tmp/binarydeb/ros-kinetic-ros-mpg321-player-0.1.0/debian/ros-kinetic-ros-mpg321-player/opt/ros/kinetic/share/ros_mpg321_player/cmake/ros_mpg321_playerConfig-version.cmake
10:22:10 -- Installing: /tmp/binarydeb/ros-kinetic-ros-mpg321-player-0.1.0/debian/ros-kinetic-ros-mpg321-player/opt/ros/kinetic/share/ros_mpg321_player/package.xml
10:22:10 -- Installing: /tmp/binarydeb/ros-kinetic-ros-mpg321-player-0.1.0/debian/ros-kinetic-ros-mpg321-player/opt/ros/kinetic/lib/ros_mpg321_player/ros_mpg321_player
10:22:10 -- Set runtime path of "/tmp/binarydeb/ros-kinetic-ros-mpg321-player-0.1.0/debian/ros-kinetic-ros-mpg321-player/opt/ros/kinetic/lib/ros_mpg321_player/ros_mpg321_player" to ""
10:22:10 CMake Error at cmake_install.cmake:71 (file):
10:22:10   file INSTALL cannot find
10:22:10   "/tmp/binarydeb/ros-kinetic-ros-mpg321-player-0.1.0/ros_mpg321_player/ros_mpg321_player".
10:22:10 
10:22:10 
10:22:10 Makefile:64: recipe for target 'install' failed
10:22:10 make[2]: *** [install] Error 1
```

**Comment by robotpilot** [comment]
@tfoote, I don't understand the mean 'bad install rule'. Please give me some tips.

**Comment by tfoote** [comment]
It's trying to install a file that doesn't exist or into a location that does not exist. You should be able to reproduce this with any of the build types that install such as `catkin_make_isolated --install`

**Comment by robotpilot** [comment]
Hi @tfoote,
I tried it. It is not a problem in my case. The file exists exact folder.

pyo@pyo:~/catkin_ws$ catkin_make_isolated --install
Base path: /home/pyo/catkin_ws
Source space: /home/pyo/catkin_ws/src
Build space: /home/pyo/catkin_ws/build_isolated
Devel space: /home/pyo/catkin_ws/devel_isolated
Install space: /home/pyo/catkin_ws/install_isolated

```
~~  traversing 2 packages in topological order:
~~  - robotis_utility
~~  - ros_mpg321_player
```

The packages or cmake arguments have changed, forcing cmake invocation

==> Processing catkin package: 'robotis_utility'
==> Creating build directory: 'build_isolated/robotis_utility'
==> cmake /home/pyo/catkin_ws/src/ROBOTIS-Utility/robotis_utility -DCATKIN_DEVEL_PREFIX=/home/pyo/catkin_ws/devel_isolated/robotis_utility -DCMAKE_INSTALL_PREFIX=/home/pyo/catkin_ws/install_isolated -G Unix Makefiles in '/home/pyo/catkin_ws/build_isolated/robotis_utility'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/pyo/catkin_ws/devel_isolated/robotis_utility
-- Using CMAKE_PREFIX_PATH: /home/pyo/catkin_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/pyo/catkin_ws/build_isolated/robotis_utility/test_results
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pyo/catkin_ws/build_isolated/robotis_utility
==> make -j8 -l8 in '/home/pyo/catkin_ws/build_isolated/robotis_utility'
==> make install in '/home/pyo/catkin_ws/build_isolated/robotis_utility'
Install the project...
-- Install configuration: ""
-- Installing: /home/pyo/catkin_ws/install_isolated/_setup_util.py
-- Installing: /home/pyo/catkin_ws/install_isolated/env.sh
-- Installing: /home/pyo/catkin_ws/install_isolated/setup.bash
-- Installing: /home/pyo/catkin_ws/install_isolated/setup.sh
-- Installing: /home/pyo/catkin_ws/install_isolated/setup.zsh
-- Installing: /home/pyo/catkin_ws/install_isolated/.rosinstall
-- Installing: /home/pyo/catkin_ws/install_isolated/share/robotis_utility/package.xml
<== Finished processing package [1 of 2]: 'robotis_utility'

==> Processing catkin package: 'ros_mpg321_player'
==> Creating build directory: 'build_isolated/ros_mpg321_player'
==> Building with env: '/home/pyo/catkin_ws/install_isolated/env.sh'
==> cmake /home/pyo/catkin_ws/src/ROBOTIS-Utility/ros_mpg321_player -DCATKIN_DEVEL_PREFIX=/home/pyo/catkin_ws/devel_isolated/ros_mpg321_player -DCMAKE_INSTALL_PREFIX=/home/pyo/catkin_ws/install_isolated -G Unix Makefiles in '/home/pyo/catkin_ws/build_isolated/ros_mpg321_player'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/pyo/catkin_ws/devel_isolated/ros_mpg321_player
-- Using CMAKE_PREFIX_PATH: /home/pyo/catkin_ws/install_isolated;/opt/ros/kinetic
-- This workspace overlays: /home/pyo/catkin_ws/install_isolated;/opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/pyo/catkin_ws/build_isolated/ros_mpg321_player/test_results
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pyo/catkin_ws/build_isolated/ros_mpg321_player
==> make -j8 -l8 in '/home/pyo/catkin_ws/build_isolated/ros_mpg321_player'
Scanning dependencies of target roscpp_generate_messages_py
Scanning dependencies of target rosgraph_msgs_generate_messages_nodejs
Scanning dependencies of target roscpp_generate_messages_lisp
Scanning dependencies of target std_msgs_generate_messages_cpp
Scanning dependencies of target rosgraph_msgs_generate_messages_cpp
Scanning dependencies of target rosgraph_msgs_generate_messages_eus
Scanning dependencies of target std_msgs_generate_messages_eus
Scanning dependencies of target std_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_eus
Scanning dependencies of target roscpp_generate_messages_nodejs
Scanning dependencies of target roscpp_generate_messages_cpp
Scanning dependencies of target rosgraph_msgs_generate_messages_py
Scanning dependencies of target rosgraph_msgs_generate_messages_lisp
Scanning dependencies of target std_msgs_generate_messages_py
Scanning dependencies of target roscpp_generate_messages_eus
Scanning dependencies of target std_msgs_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target roscpp_generate_messages_eus
Scanning dependencies of target ros_mpg321_player
[ 50%] Building CXX object CMakeFiles/ros_mpg321_player.dir/src/ros_mpg321_player.cpp.o
**[100%] Linking CXX executable /home/pyo/catkin_ws/devel_isolated/ros_mpg321_player/lib/ros_mpg321_player/ros_mpg321_player
[100%] Built target ros_mpg321_player**
==> make install in '/home/pyo/catkin_ws/build_isolated/ros_mpg321_player'
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_lisp
[100%] Built target ros_mpg321_player
Install the project...
-- Install configuration: ""
-- Installing: /home/pyo/catkin_ws/install_isolated/_setup_util.py
-- Installing: /home/pyo/catkin_ws/install_isolated/env.sh
-- Installing: /home/pyo/catkin_ws/install_isolated/setup.bash
-- Installing: /home/pyo/catkin_ws/install_isolated/setup.sh
-- Installing: /home/pyo/catkin_ws/install_isolated/setup.zsh
-- Installing: /home/pyo/catkin_ws/install_isolated/.rosinstall
-- Installing: /home/pyo/catkin_ws/install_isolated/lib/pkgconfig/ros_mpg321_player.pc
-- Installing: /home/pyo/catkin_ws/install_isolated/share/ros_mpg321_player/cmake/ros_mpg321_playerConfig.cmake
-- Installing: /home/pyo/catkin_ws/install_isolated/share/ros_mpg321_player/cmake/ros_mpg321_playerConfig-version.cmake
-- Installing: /home/pyo/catkin_ws/install_isolated/share/ros_mpg321_player/package.xml
-- Installing: /home/pyo/catkin_ws/install_isolated/lib/ros_mpg321_player/ros_mpg321_player
-- Set runtime path of "/home/pyo/catkin_ws/install_isolated/lib/ros_mpg321_player/ros_mpg321_player" to ""
-- Installing: /home/pyo/catkin_ws/install_isolated/include/ros_mpg321_player
-- Installing: /home/pyo/catkin_ws/install_isolated/include/ros_mpg321_player/ros_mpg321_player.h
**<== Finished processing package [2 of 2]: 'ros_mpg321_player'**

**Comment by tfoote** [comment]
That's odd. I don't know where the file path "/tmp/binarydeb/ros-kinetic-ros-mpg321-player-0.1.0/ros_mpg321_player/ros_mpg321_player" is coming from.  Maybe @dirk-thomas would see where it's coming from.

**Comment by robotpilot** [comment]
Thank you for your supports. :)

**Comment by dirk-thomas** [comment]
As the error message indicates the directory `ros_mpg321_player/ros_mpg321_player` specified for installation doesn't exist. Therefore the `install` rule failes (https://github.com/ROBOTIS-GIT-release/ROBOTIS-Utility-release/blob/9ff8f6902eae549f231c5e288e728e6d3243996a/CMakeLists.txt#L49). It looks like you have already found the problem a month ago and have addressed it on the master branch: 1f8a76c7cca126d305dccb2e4a0b87bb8970b9b8 But you have to release a new version in order to update the code in the release repo and therefore the sourcedeb.

**Comment by dirk-thomas** [comment]
It looks like you have tried to "update" the previous tag `0.1.0` after it had already been released since in this repo the CMake file on the tag already contains the fix. You should not change tags after the fact but instead make a new patch release. The release repo still contains the original version you called `0.1.0` before the patch. You could do a debinc release now but I highly recommend to just make a patch release and call the new version `0.1.1`.

**Comment by robotpilot** [comment]
Thanks, @dirk-thomas  . Thanks to you detailed info, I understand clearly. I will continue release works. Thanks again. :)
